addSbtPlugin("org.scoverage"           % "sbt-scoverage"       % "1.9.3")
addSbtPlugin("com.sonar-scala"         % "sbt-sonar"           % "2.3.0")
addSbtPlugin("com.typesafe.sbt"        % "sbt-native-packager" % "1.8.0")
addSbtPlugin("com.beautiful-scala"     % "sbt-scalastyle"      % "1.5.1")
addSbtPlugin("com.sksamuel.scapegoat" %% "sbt-scapegoat"       % "1.1.1")
addSbtPlugin("io.chrisdavenport"      %% "sbt-make-pom"        % "0.0.3")
